package org.grails.cxf.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-05-18T12:31:31.653+03:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://webservice.cff3.jevera.com/", name = "ForecastService")
@XmlSeeAlso({ObjectFactory.class})
public interface ForecastService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "forecast", targetNamespace = "http://webservice.cff3.jevera.com/", className = "org.grails.cxf.soap.Forecast")
    @WebMethod
    @ResponseWrapper(localName = "forecastResponse", targetNamespace = "http://webservice.cff3.jevera.com/", className = "org.grails.cxf.soap.ForecastResponse")
    public org.grails.cxf.soap.ForecastResult forecast(
        @WebParam(name = "request", targetNamespace = "")
        org.grails.cxf.soap.ForecastRequest request
    );
}
