package org.grails.cxf.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-05-18T12:31:31.719+03:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ForecastServiceAPI", 
                  wsdlLocation = "file:/D:/cff3/саа3_service_api/ForecastServiceAPI.wsdl",
                  targetNamespace = "http://webservice.cff3.jevera.com/") 
public class ForecastServiceAPI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.cff3.jevera.com/", "ForecastServiceAPI");
    public final static QName ForecastServicePort = new QName("http://webservice.cff3.jevera.com/", "ForecastServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/cff3/саа3_service_api/ForecastServiceAPI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ForecastServiceAPI.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/cff3/саа3_service_api/ForecastServiceAPI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ForecastServiceAPI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ForecastServiceAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ForecastServiceAPI() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ForecastServiceAPI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ForecastServiceAPI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ForecastServiceAPI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ForecastService
     */
    @WebEndpoint(name = "ForecastServicePort")
    public ForecastService getForecastServicePort() {
        return super.getPort(ForecastServicePort, ForecastService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ForecastService
     */
    @WebEndpoint(name = "ForecastServicePort")
    public ForecastService getForecastServicePort(WebServiceFeature... features) {
        return super.getPort(ForecastServicePort, ForecastService.class, features);
    }

}
